server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shortlinks?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: ${ES_URIS:http://localhost:9200}
    username: ${ES_USER:}
    password: ${ES_PASSWORD:}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shortlinks.search.entity

elasticsearch:
  index:
    name: shortlinks
    shards: 1
    replicas: 1
