server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shortlinks?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shortlinks.shortlink.entity

shortlink:
  domain: ${SHORTLINK_DOMAIN:http://localhost:8081}
  length: 6
  cache:
    expire-time: 3600
